name: Docker Image CI

on: workflow_dispatch
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: Clone
      run: git clone git@github.com:luansmartr/smartr-env.git
    - name: Test
      run: ls
#     - name: Build and push
#       run: | 
#         echo ${{ secrets.SSH_KEY }}
#       uses: docker/build-push-action@v4
#       with:
#         load: true
#         tags: test-repo-clone:latest
#         secrets: "github=${{ secrets.SSH_KEY }}"
#     - name: Test
#       run: |
#           docker run --rm test-repo-clone:latest
